/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LESS = 5;
  /** RegularExpression Id. */
  int GREATER = 6;
  /** RegularExpression Id. */
  int LEQ = 7;
  /** RegularExpression Id. */
  int GEQ = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int IN = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int BOOL = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int PRINTLN = 20;
  /** RegularExpression Id. */
  int ASSIGN = 21;
  /** RegularExpression Id. */
  int EQCOMP = 22;
  /** RegularExpression Id. */
  int NEQCOMP = 23;
  /** RegularExpression Id. */
  int NEW = 24;
  /** RegularExpression Id. */
  int SEQ = 25;
  /** RegularExpression Id. */
  int NEG = 26;
  /** RegularExpression Id. */
  int DEREF = 27;
  /** RegularExpression Id. */
  int ANY_STRING = 28;
  /** RegularExpression Id. */
  int DEF = 29;
  /** RegularExpression Id. */
  int Id = 30;
  /** RegularExpression Id. */
  int Num = 31;
  /** RegularExpression Id. */
  int PLUS = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int TIMES = 34;
  /** RegularExpression Id. */
  int DIV = 35;
  /** RegularExpression Id. */
  int LPAR = 36;
  /** RegularExpression Id. */
  int RPAR = 37;
  /** RegularExpression Id. */
  int EQ = 38;
  /** RegularExpression Id. */
  int DOUBLESEQ = 39;
  /** RegularExpression Id. */
  int LBRA = 40;
  /** RegularExpression Id. */
  int RBRA = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"in\"",
    "\"end\"",
    "<BOOL>",
    "\"print\"",
    "\"println\"",
    "\":=\"",
    "\"==\"",
    "\"!=\"",
    "\"new\"",
    "\";\"",
    "\"~\"",
    "\"!\"",
    "<ANY_STRING>",
    "\"let\"",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";;\"",
    "\"{\"",
    "\"}\"",
  };

}
